version: 2
updates:

  # Workflow files stored in the default location of `.github/workflows`
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "github-actions"

- package-ecosystem: "npm"
  # Files stored in `app` directory
  directory: "/app"
  schedule:
    interval: "daily"
commit-message:
  prefix: "npm"

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "nuget"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
